definitions:
  models.User:
    properties:
      cpf:
        type: string
      created_at:
        type: string
      data_nascimento:
        type: string
      email:
        type: string
      id:
        type: integer
      nome:
        type: string
      password:
        type: string
      perfil:
        type: string
      updated_at:
        type: string
    type: object
  models.UserLogin:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  models.UserResponse:
    properties:
      cpf:
        type: string
      created_at:
        type: string
      data_nascimento:
        type: string
      email:
        type: string
      has_permission:
        description: Permissão para operações específicas
        type: boolean
      id:
        type: integer
      is_admin:
        description: Verificação de permissão
        type: boolean
      nome:
        type: string
      perfil:
        type: string
      updated_at:
        type: string
    type: object
info:
  contact: {}
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Autentica um usuário com email e senha
      parameters:
      - description: Dados de login
        in: body
        name: loginData
        required: true
        schema:
          $ref: '#/definitions/models.UserLogin'
      produces:
      - application/json
      responses:
        "200":
          description: Login realizado com sucesso
          schema:
            $ref: '#/definitions/models.UserResponse'
        "400":
          description: JSON inválido ou campos obrigatórios ausentes
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Credenciais inválidas
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login de usuário
      tags:
      - Autenticação
  /register:
    post:
      consumes:
      - application/json
      description: Cadastra um novo usuário no sistema
      parameters:
      - description: 'Dados do usuário (perfil é opcional, padrão: ''user'')'
        in: body
        name: userData
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "201":
          description: Usuário cadastrado com sucesso
          schema:
            $ref: '#/definitions/models.UserResponse'
        "400":
          description: JSON inválido, campos obrigatórios ausentes ou perfil inválido
          schema:
            additionalProperties:
              type: string
            type: object
        "409":
          description: Email ou CPF já cadastrado
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Erro interno do servidor
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Cadastro de usuário
      tags:
      - Autenticação
  /users:
    get:
      consumes:
      - application/json
      description: Retorna a lista de todos os usuários cadastrados com informações
        de perfil e permissões
      produces:
      - application/json
      responses:
        "200":
          description: Lista de usuários com total e mensagem
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Erro interno do servidor
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Listar todos os usuários
      tags:
      - Usuários
  /users/check:
    get:
      consumes:
      - application/json
      description: Endpoint de debug para verificar se a tabela users existe e está
        funcionando
      produces:
      - application/json
      responses:
        "200":
          description: Status da tabela users
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Tabela users não encontrada
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Erro interno do servidor
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Verificar status da tabela users
      tags:
      - Debug
  /users/permissions:
    get:
      consumes:
      - application/json
      description: Verifica as permissões de um usuário específico baseado no email
      parameters:
      - description: Email do usuário
        in: query
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Informações do usuário e suas permissões
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Email é obrigatório
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Usuário não encontrado
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Verificar permissões do usuário
      tags:
      - Usuários
  /users/profile:
    get:
      consumes:
      - application/json
      description: Retorna usuários filtrados por perfil (admin ou user)
      parameters:
      - description: Perfil do usuário
        enum:
        - admin
        - user
        in: query
        name: profile
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Lista de usuários do perfil especificado
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Parâmetro profile obrigatório ou perfil inválido
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Erro interno do servidor
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Listar usuários por perfil
      tags:
      - Usuários
swagger: "2.0"
